### ISSUE TITLE
Error on Shutdown

### ISSUE THREAD

**Issue by Commandcracker** [Folia-Inquisitors/WorldEdit-Folia#1]
### WorldEdit Version

v7.3.0-SNAPSHOT+12866a7

### Platform Version

This server is running Folia version git-Folia-"7bc26ec" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7bc26ec on dev/1.20.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

```
[19:04:33 ERROR]: Error occurred while disabling WorldEdit v7.3.0-SNAPSHOT+12866a7
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:346) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onDisable(WorldEditPlugin.java:324) ~[worldedit-bukkit-7.3.0-SNAPSHOT-Custom-Folia-dist.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:149) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:574) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1049) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:830) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
        at io.papermc.paper.threadedregions.RegionShutdownThread.run(RegionShutdownThread.java:136) ~[folia-1.20.4.jar:git-Folia-"7bc26ec"]
```

### Expected Behavior

No Errors

### Reproduction Steps

1. Run `stop`
2. See Error

**Comment by Yomamaeatstoes** [comment]
Since this is on shutdown this is not a issue

**Comment by Yomamaeatstoes** [comment]
I will keep it open so others are aware
