### ISSUE TITLE
Failed on Startup

### ISSUE THREAD

**Issue by Brrrtk** [Folia-Inquisitors/WorldEdit-Folia#6]
### WorldEdit Version

7.3.5

### Platform Version

Folia 1.21.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[00:52:23 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to open plugin jar plugins/worldedit-bukkit-7.3.5.jar
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
        at io.papermc.paper.pluginremap.PluginRemapper.waitForAll(PluginRemapper.java:410) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:206) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at net.minecraft.server.Main.main(Main.java:125) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to open plugin jar plugins/worldedit-bukkit-7.3.5.jar
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:339) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        ... 9 more
Caused by: java.util.zip.ZipException: zip END header not found
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1541) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528) ~[?:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:440) ~[?:?]
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:290) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[folia-1.21.4.jar:1.21.4-1-8af1aef]
        ... 9 more
        
        help please lol
        

### Expected Behavior

It should work

### Reproduction Steps

1. Launched

**Comment by Brrrtk** [comment]
nvm im just f* stupid
